name: Auto Commit to Keep Contributions Active

on:
  schedule:
    - cron: "0 6,18 * * *"  # Runs at 6 AM and 6 PM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures we fetch the full history to avoid merge conflicts

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull latest changes
        run: |
          git pull origin main --rebase  # Ensure the latest changes are merged

      - name: Make a dummy commit
        run: |
          echo "$(date)" >> dummy.txt
          git add dummy.txt
          git commit -m "Auto commit: $(date)"
          
      - name: Push changes
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
