name: Auto Commit to Keep Contributions Active

on:
  schedule:
    - cron: "0 4,8,12,16,20,24 * * *"  
  workflow_dispatch: 

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures we fetch the full history

      - name: Set up Git with Your Identity
        run: |
          git config --global user.name "sankalp2102"  
          git config --global user.email "sankalpgupta444@gmail.com"

      - name: Pull latest changes
        run: |
          git pull origin main --rebase  # Avoid conflicts

      - name: Make a dummy commit
        run: |
          echo "$(date)" >> dummy.txt
          git add dummy.txt
          git commit -m "Auto commit: $(date)" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin main
