name: Generate GitHub Contribution Snake Animation
on:
  schedule:
    - cron: "0 6,18,20 * * *"  # Runs at 6 AM, 6 PM, and 8 PM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Generate Snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: sankalp2102
          svg_out_path: dist/github-contribution-grid-snake.svg
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=blue&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            dist/neon.gif?color_snake=#33ff00&color_dots=#000000,#111111,#222222,#333333,#444444
            dist/fire.gif?color_snake=#ff3300&color_dots=#ffcc00,#ff9900,#ff6600,#ff3300,#cc0000
            dist/rainbow.gif?color_snake=rainbow&color_dots=#ff0000,#ffa500,#ffff00,#008000,#0000ff,#4b0082,#ee82ee
          snake_color: rainbow
          gif_out_path: dist/github-contribution-grid-snake.gif
          
      - name: Push the Snake animation to the repo
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
