name: Generate Super Cool GitHub Contribution Snake Animation
on:
  schedule:
    - cron: "0 6,18,20 * * *"  # Runs at 6 AM, 6 PM, and 8 PM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Generate Snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: sankalp2102
          outputs: |
            # Super vibrant, high-contrast neon theme
            dist/neon-hyperdrive.gif?color_snake=#00ffff&color_dots=#000000,#111111,#222222,#333333,#9000ff
            
            # Cyberpunk theme with animated gradient
            dist/cyberpunk.gif?color_snake=gradient,#ff00ff,#00ffff,#ffff00&color_dots=#000000,#550055,#005555,#555500,#222222
            
            # Matrix-inspired theme
            dist/matrix.gif?color_snake=#00ff00&color_dots=#000000,#001100,#002200,#003300,#004400&bg_color=#000000
            
            # Aurora borealis effect
            dist/aurora.gif?color_snake=gradient,#9400D3,#4B0082,#0000FF,#00FF00,#FFFF00,#FF7F00,#FF0000&color_dots=#000000,#111111,#222222,#333333,#444444&bg_color=#000000
            
            # Fire and ice contrast
            dist/fire-ice.gif?color_snake=gradient,#00ccff,#0066ff,#ff3300,#ff6600&color_dots=#000033,#000066,#330000,#660000
            
            # Synthwave sunset
            dist/synthwave.gif?color_snake=gradient,#ff00ff,#ff3377,#ff6655,#ffcc00&color_dots=#220033,#330044,#440055,#550066,#660077
          snake_color: gradient,#ff00ff,#00ffff,#ffff00,#33ff00
          
      - name: Push the Snake animation to the repo
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
